### ISSUE TITLE
記一下

### ISSUE THREAD

**Issue by kakas** [williamafil/inv_mgmt#1]
1. 需要有 github 的權限
1. 需要有 DB 的資料可以測試
1. ruby 可以升到 2.3.3

想到再加...

**Comment by williamafil** [comment]
- [ O ] 需要有 github 的權限
- [ O ] 需要有 DB 的資料可以測試
- [ X ] ruby 可以升到 2.3.3

我2.3.3安裝失敗, 奇怪了.....
